# Generated by Django 3.1.3 on 2020-11-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.BigIntegerField()),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('profile', models.ImageField(default='pic.jpg', upload_to='')),
            ],
        ),
    ]
