# Generated by Django 3.1.3 on 2020-11-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='-', max_length=500)),
                ('English_name', models.CharField(default='-', max_length=500)),
                ('irrigation_quantity', models.CharField(blank=True, choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], default='-', max_length=10, null=True)),
                ('irrigation', models.CharField(blank=True, default='-', max_length=10000, null=True)),
                ('temprature_quantity', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('temprature', models.CharField(blank=True, default='-', max_length=10000, null=True)),
                ('light_quantity', models.CharField(blank=True, choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], default='-', max_length=10, null=True)),
                ('light', models.CharField(blank=True, default='-', max_length=10000, null=True)),
                ('humidity_quantity', models.CharField(blank=True, choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], default='-', max_length=10, null=True)),
                ('humidity', models.CharField(blank=True, default='-', max_length=10000, null=True)),
                ('soil', models.CharField(blank=True, default='-', max_length=10000, null=True)),
                ('fertilizer', models.CharField(blank=True, default='-', max_length=10000, null=True)),
                ('problems', models.CharField(blank=True, default='-', max_length=10000, null=True)),
                ('potting', models.CharField(blank=True, default='-', max_length=10000, null=True)),
                ('poisonous', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='-', max_length=5, null=True)),
                ('sensibility', models.CharField(blank=True, choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], default='-', max_length=10, null=True)),
            ],
        ),
    ]
