# Generated by Django 3.1.3 on 2020-11-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20201114_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='fertilizer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='humidity',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='humidity_quantity',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='irrigation',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='irrigation_quantity',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='light',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='light_quantity',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='poisonous',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='potting',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='problems',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sensibility',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='temprature',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='temprature_quantity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
